praktikum/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
# import story_1.urls as story_1
import story_3.urls as story_3
import story_5.urls as story_5

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^', include(story_1, namespace='story-1')), 
    url(r'^', include(story_3, namespace='story-3')),
    url(r'^schedule/', include(story_5, namespace='story-5')),
]

story_1/urls.py
from django.conf.urls import url
from .views import index

app_name = 'story_1'

urlpatterns = [
    url(r'^$', index, name='index'),
]

story_3/urls.py
from django.conf.urls import url
from .views import index, about, register

app_name = 'story_3'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^about/', about, name='about'),
    url(r'^register/', register, name='register'),
]

story_5/urls.py
from django.conf.urls import url
from .views import index, add_activity, delete_all

app_name = 'story_5'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_activity', add_activity, name='add_activity'),
    url(r'^delete_all', delete_all, name='delete_all'),
]

story_1/models.py
from django.db import models

# Create your models here.

story_3/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

# Create your models here.
class Activity(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    time = models.TimeField()
    place = models.CharField(max_length=100)
    category = models.CharField(max_length=75)

story_5/forms.py
from django import forms
# import datetime

class Schedule_Form(forms.Form):
    attrs = {'class':'form-control'}
    attrs_date = {'type':'date'}
    attrs_time = {'type':'time'}
    name = forms.CharField(label='Activity Name', max_length=50, required=True,
        widget=forms.TextInput(attrs=attrs))
    date = forms.DateField(label='Date', required=False,
        widget=forms.DateInput(attrs={**attrs, **attrs_date}))
    time = forms.TimeField(label='Time', required=False,
        widget=forms.TimeInput(attrs={**attrs, **attrs_time}))
    place = forms.CharField(label='Place', max_length=100, required=True,
        widget=forms.TextInput(attrs=attrs))
    category = forms.CharField(label='Category', max_length=75, required=True,
        widget=forms.TextInput(attrs=attrs))

story_1/views.py
from django.shortcuts import render

# Create your views here.
response = {}

def index(request):
    return render(request, 'index_story1.html', response)

story_3/views.py
from django.shortcuts import render

# Create your views here.
response = {}

def index(request):
    return render(request, 'story_3_home.html', response)

def about(request):
    return render(request, 'story_3_about.html', response)
    
def register(request):
    return render(request, 'story_3_register.html', response)

story_5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from datetime import datetime, date
from .forms import Schedule_Form
from .models import Activity

# Create your views here.
response = {}
html = 'story_5_jadwal.html'


def index(request):
    form = Schedule_Form()
    response['form'] = form

    activity_list = Activity.objects.all().values()
    activity_dict = convert_queryset_into_json(activity_list)
    response['activity_dict'] = activity_dict[::-1]

    return render(request, html, response)

def add_activity(request):
    form = Schedule_Form(request.POST or None)
    response['form'] = form
    if (request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['date'] = request.POST['date'] if request.POST['date'] != '' else datetime.now().strftime("%Y-%m-%d")
        response['time'] = request.POST['time'] if request.POST['time'] != '' else datetime.now().strftime("%X")
        response['place'] = request.POST['place']
        response['category'] = request.POST['category']
        activity = Activity(name=response['name'],
            date=response['date'],
            time=response['time'],
            place=response['place'],
            category=response['category']
        )
        activity.save()
        return HttpResponseRedirect('/schedule')
    else:
        return HttpResponseRedirect('/')

def delete_all(request):
    Activity.objects.all().delete()
    return HttpResponseRedirect('/schedule')
        
def convert_queryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

story_1/templates/index_story1.html
<head>
    <style>

        body {
            background-color: lightgrey;
        }
        div {
            background-color: white;
            width: 500px;
            border: 1px solid gray;
            padding: 25px;
            margin: auto;
            margin-bottom: 10px;  
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        p {
            font-family: 'Rubik', sans-serif;
            font-size: 15px;
        }
    </style>
</head>

<div>
    {% load static %}
    <img  src="{% static '../static/reyhan.jpg' %} " alt="Reyhan Alhafizal Hamidi" height="30%">
    <!-- <img src="https://gitlab.com/reyhanhamidi/ppw/raw/master/story_1/static/reyhan.jpg" alt="Reyhan Alhafizal Hamidi" height="30%"> -->
    <p>
        Name&emsp;&emsp;&emsp;: Reyhan Alhafizal Hamidi
        <br>
        NPM&emsp;&emsp;&emsp;&ensp;: 1706040082
        <br>
        Jurusan&emsp;&emsp;: Ilmu Komputer
        <br>
        Universitas&ensp; : UI
        <br>
        Hobi&emsp;&emsp;&emsp;&ensp;: Belajar
    </p>

    <p>
        Halo, saya Reyhan. Saya adalah mahasiswa Ilmu Komputer UI 2017
        Saya sangat senang mempelajari hal baru di bidang ini.
        Di waktu luang, saya biasanya menonton film atau membaca komik.
        Semoga PPW lancar amin.
    </p>
</div>

<div>
        <!-- {% load static %} -->
        <!-- <img src="{% static '../static/dafa.jpg' %}" alt="Dafa Ramadansyah's photo" height="30%"> -->
        <img src="https://gitlab.com/Darrand/PPW-Darrand/raw/master/lab_1/static/dafa.jpg" alt="Dafa Ramadansyah's photo" height="30%">
        <p>
            Name&emsp;&emsp;&emsp;: Dafa Ramadansyah
            <br>
            NPM&emsp;&emsp;&emsp;&ensp;: 1706039370
            <br>
            Jurusan&emsp;&emsp;: Ilmu Komputer
            <br>
            Universitas&ensp; : UI
            <br>
            Hobi&emsp;&emsp;&emsp;&ensp;: Game, Musik, dan Film
        </p>
    
        <p>
                My name is Dafa Ramadansyah, currently 19 years old in living. I was born in 8th of January 1999.
                I have 1 sister and 1 brother both are older. I am currently pursuing my study in computer science 
                field at Universitas Indonesia. My hobbies are playing video games, listening to music and watching 
                all kind of shows (e.g. movies, animes, tv shows).
        </p>
</div>

<div>
        <!-- {% load static %} .-->
        <!-- <img src="{% static '../static/bimo.jpg' %}" alt="Bimo Iman's photo" height="30%"> -->
        <img src="https://gitlab.com/bimo.iman1/pepewee/raw/master/lab_1/templates/Profile%20pict.JPG" alt="Bimo Iman's photo" height="30%">
        <p>
            Name&emsp;&emsp;&emsp;: Bimo Iman Smartadi
            <br>
            NPM&emsp;&emsp;&emsp;&ensp;: 1706039780
            <br>
            Jurusan&emsp;&emsp;: Ilmu Komputer
            <br>
            Universitas&ensp; : UI
            <br>
            Hobi&emsp;&emsp;&emsp;&ensp;: Game, Musik, dan Film
        </p>
    
        <p>
                A bald guy DC Comic Enthusiast.
        </p>
</div>

story_3/templates/base.html
<!doctype html>
<html lang="en">
  
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story_3.css' %}">

    <title>[ R ] Hi, I'm BluRey8.</title>
  </head>

  <body>

    <!-- Navbar -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark ">
        
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-md-center" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
            <a class="navbar-brand" href="/">[ R ]</a>
            <a class="nav-item nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="/about#Education">Education</a>
            <a class="nav-item nav-link" href="/about#Skill">Skill</a>
            <a class="nav-item nav-link" href="/about#Experience">Experience</a>
            <a class="nav-item nav-link" href="/about#Achievement">Achievement</a>
            <a class="nav-item nav-link" href="/about#Contact">Contact</a>
            <a class="nav-item nav-link" href="/schedule">Activity</a>
          </div>
      </div>
    </nav>
    
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

story_3/templates/story_3_about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container  ">            
  <!-- Education -->
  <div class="row full-height section mx-0 my-3 px-2 px-md-0 py-3 d-flex flex-md-row justify-content-center"
    id="Education">
    <div class="media col-sm-8 align-self-center ">
      <div class="row">
        <!-- <div class="col-sm-5 align-self-center "> -->
          <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'ui.png' %}" alt="An Icon" 
            width="25%">
        <!-- </div> -->
        <div class="media-body col-sm align-self-center">
          <h2 class="mt-0 title-2">University of Indonesia</h2>
          <h3 class="mt-0 subtitle-2">Student of Computer Science</h3>
          <h3 class="mt-0 subtitle-2">2017-2021</h3>
            <p>Perform good in academic and non-academic activity. 
              Currently a Teaching Assistant.</p>
        </div>
      </div>
    </div>
    <div class="media col-sm-8 align-self-center ">
      <div class="media-body align-self-center">
        <h2 class="mt-0 title-2">SMAN 1 Tangerang</h2>
        <h3 class="mt-0 subtitle-2">2014-2017</h3>
        <p>Arguably best high school in town. Active in High School Organization 
          including Student Council and Head of IT Club.</p>
        </div>
        <img class="img-fluid align-self-center ml-3" src="{% static 'smanitra.png' %}"alt="An Icon" 
          width="25%">
      </div>
  </div>

  <!-- Skills -->
  <div class="row full-height section  mx-0 my-3 px-0 py-3 d-flex flex-md-row justify-content-center"
  id="Skill">
    <!-- <div class=" "> -->
    <!-- Language -->
    <div class="col-sm col-md-6 align-self-center ">
      <div class="row">

        <div class="col-sm-4 align-self-center  ">
          <div class="title-3 my-2">Java</div>
        </div>
        <div class="col-sm-8 align-self-center  ">
          <div class="progress  ">
            <div class="progress-bar" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
        <div class="w-100"></div>

        <div class="col-sm-4 align-self-center  ">
          <div class="title-3 my-2">Python</div>
        </div>
        <div class="col-sm-8 align-self-center  ">
          <div class="progress  ">
            <div class="progress-bar" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
        <div class="w-100"></div>

        <div class="col-sm-4 align-self-center  ">
          <div class="title-3 my-2">HTML</div>
        </div>
        <div class="col-sm-8 align-self-center  ">
          <div class="progress  ">
            <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
        <div class="w-100"></div>

        <div class="col-sm-4 align-self-center  ">
          <div class="title-3 my-2">CSS</div>
        </div>
        <div class="col-sm-8 align-self-center  ">
          <div class="progress  ">
            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
        <div class="w-100"></div>

        <div class="col-sm-4 align-self-center  ">
          <div class="title-3 my-2">JavaScript</div>
        </div>
        <div class="col-sm-8 align-self-center  ">
          <div class="progress  ">
            <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
        <div class="w-100"></div>
        
      </div>
    <!-- </div> -->
    </div>

    <!-- My-Project -->
    <div class="col-sm col-md-4 align-self-center "
      id="my-project">
      <h3>My-Project</h3>
      <div class="my-3"><a>DDP 1 - Python GUI</a></div>
      <div class="my-3"><a>DDP 2 - Java GUI & CLI</a></div>
      <div class="my-3"><a>PPW - Django Website</a></div>
      {% comment %} <div class="my-3"><a>&nbsp;</a></div>
      <div class="my-3"><a>&nbsp;</a></div> {% endcomment %}
    </div>
  
  </div>

  <!-- Experience -->
  <div class="row full-height section mx-0 my-3 px-2 px-md-0 py-5 d-flex flex-md-row justify-content-center"
    id="Experience">
      
    <div class="col-md-5 px-0 align-self-center  ">
      <div class="media row-md-auto py-0 align-self-center  ">
        <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'ui.png' %}" alt="An Icon" 
          width="25%">
        <div class="media-body align-self-center mx-0  ">
          <h3 class="mt-0 title-3">Teaching Assistant</h2>
          <h5 class="mt-0 subtitle-3">At University of Indonesia</h3>
          <h5 class="mt-0 subtitle-3">2018</h3>
            <p>Teaching assistant of Introduction to Digital System for regular class</p>
        </div>
      </div>
    </div>

    <div class="col-md-5 px-0 align-self-center  ">
      <div class="media row-md-auto py-0 align-self-center  ">
        <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'compfest.jpg' %}" alt="An Icon" 
          width="25%">
        <div class="media-body align-self-center mx-0  ">
          <h3 class="mt-0 title-3">Staff of Startup Academy</h2>
          <h5 class="mt-0 subtitle-3">At COMPFEST X</h3>
          <h5 class="mt-0 subtitle-3">2018</h3>
            <p>An IT event held by Computer Science University of Indonesia</p>
        </div>
      </div>
    </div>

    <div class="w-100"></div>
    
    <div class="col-md-5 px-0 align-self-center  ">
      <div class="media row-md-auto py-0 align-self-center  ">
        <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'osis.jpg' %}" alt="An Icon" 
          width="25%">
        <div class="media-body align-self-center mx-0  ">
          <h3 class="mt-0 title-3">Staff of Student Council</h2>
          <h5 class="mt-0 subtitle-3">At SMAN 1 Tangerang</h3>
          <h5 class="mt-0 subtitle-3">2015-2016</h3>
            <p>Staff of Technology Development Division.
              Represent ITnC in Student Council.
            </p>
        </div>
      </div>
    </div>
    <div class="col-md-5 px-0 align-self-center  ">
      <div class="media row-md-auto py-0 align-self-center  ">
        <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'itnc.jpg' %}" alt="An Icon" 
          width="25%">
        <div class="media-body align-self-center mx-0  ">
          <h3 class="mt-0 title-3">Head of ITnC</h2>
          <h5 class="mt-0 subtitle-3">At SMAN 1 Tangerang</h3>
          <h5 class="mt-0 subtitle-3">2015-2016</h3>
            <p>An IT Club focusing on programming and graphic design</p>
        </div>
      </div>
    </div>


  </div>

  <!-- Achievement -->
  <div class="row full-height section mx-0 my-3 px-2 px-md-0 py-5 d-flex flex-md-row justify-content-center"
    id="Achievement">
      
      <div class="col-md-5 px-0 align-self-center  ">
        <div class="media row-md-auto py-0 align-self-center  ">
          <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'ristek.png' %}" alt="An Icon" 
            width="25%">
          <div class="media-body align-self-center mx-0  ">
            <h3 class="mt-0 title-3">Honorable Mention</h2>
            <h5 class="mt-0 subtitle-3">At CPC Pekan Ristek</h3>
            <h5 class="mt-0 subtitle-3">2017</h3>
              <p>A mini IT event held by Ristek Fasilkom UI</p>
          </div>
        </div>
      </div>

      <div class="col-md-5 px-0 align-self-center  ">
        <div class="media row-md-auto py-0 align-self-center  ">
          <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'tetra science.jpg' %}" alt="An Icon" 
            width="25%">
          <div class="media-body align-self-center mx-0  ">
            <h3 class="mt-0 title-3">1st Winner</h2>
            <h5 class="mt-0 subtitle-3">At Tetra Science's Informatics</h3>
            <h5 class="mt-0 subtitle-3">2015</h3>
              <p>Science Olympiad held by SMAN 4 Tangerang</p>
          </div>
        </div>
      </div>

      <div class="w-100"></div>

      <div class="col-md-5 px-0 align-self-center  ">
        <div class="media row-md-auto py-0 align-self-center  ">
          <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'quesscomp.png' %}" alt="An Icon" 
            width="25%">
          <div class="media-body align-self-center mx-0  ">
            <h3 class="mt-0 title-3">3rd Winner</h2>
            <h5 class="mt-0 subtitle-3">At Compiler's QuessComp</h3>
            <h5 class="mt-0 subtitle-3">2015</h3>
              <p>Teaching assistant of Introduction to Digital System for regular class</p>
          </div>
        </div>
      </div>

        <div class="col-md-5 px-0 align-self-center  ">
          <div class="media row-md-auto py-0 align-self-center  ">
            <img class="img-fluid rounded-circle align-self-center mr-3" src="{% static 'OSN.jpg' %}" alt="An Icon" 
              width="25%">
            <div class="media-body align-self-center mx-0  ">
              <h3 class="mt-0 title-3">Participant</h2>
              <h5 class="mt-0 subtitle-3">At OSK Informatika Tangerang</h3>
              <h5 class="mt-0 subtitle-3">2015-2016</h3>
                <p>Represent SMAN 1 Tangerang for OSK in Tangerang</p>
            </div>
          </div>
        </div>

    </div>

  
  <div class="row section mx-0 my-3 px-2 px-md-0 py-5 d-flex flex-md-row justify-content-center"
    id="Contact">
    <div class="col-md-auto text-center my-5" id="find-me">Find me!</div>
    
    <div class="w-100"></div>
    <!-- <div class="col-md-12  "> -->
    <img class="img-responsive img-contact mx-3 mb-5" src="{% static 'gitlab.png' %}" alt="Reyhan's Gitlab">
    <img class="img-responsive img-contact mx-3 mb-5" src="{% static 'gmail.png' %}" alt="Reyhan's Email" >
    <img class="img-responsive img-contact mx-3 mb-5" src="{% static 'line.png' %}" alt="Reyhan's Line" >
    <img class="img-responsive img-contact mx-3 mb-5" src="{% static 'linkedin.png' %}" alt="Reyhan's Linkedin" >
    <!-- </div> -->

  </div>

</div>
  <!-- Footer -->
  <footer class="page-footer font-small  ">

    <!-- Copyright -->
    <div class="footer-copyright text-center align-items-end">created by: blurey8 | wireframe
    </div>
    <!-- Copyright -->
  
  </footer>
{% endblock content %}

story_3/templates/story_3_home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container ">      
  <div class="row md section full-height mx-0 my-3 px-0 py-5 d-flex flex-md-row justify-content-center">
  
    <!-- Home Profile -->
    <div class="media col-8 align-self-center justify-content-center">
      <div class="row  justify-content-center">
    <div class="col-md-5 align-self-center">
      <img class="img-fluid rounded align-self-center mr-3" src="{% static 'reyhan.jpg' %}" alt="Profile Photo" 
        width="100%">
    </div>
      <div class="media-body col-md-6 align-self-center">
        <h1 class="mt-0">Reyhan Alhafizal Hamidi</h1>
          <p id="desc">Second-year Computer Science student with passion on IT development. 
          Extremely motivated to learn new things and meet new people.</p>
      </div>
      </div>
    </div>
    
    <!-- Force next columns to break to new line -->
    <div class="w-100"></div>
    <div class="mb-0 ">
      <button type="button" onclick="location.href='about/'" class="btn btn-cyan">Know Me More!</button>
    </div>
  </div>
</div>

  <!--
  <div class="row border mx-0 my-3 px-0 py-3 d-flex flex-md-row justify-content-center">
    isi container
  </div>
  -->
{% endblock content %}

story_3/templates/story_3_register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row border full-height mx-0 mt-3 px-0 py-3 d-flex flex-md-row justify-content-center">

    <!-- Default form register start -->
    <form class="text-center col-12 col-lg-5 border border-light p-3">

      <p class="h4 mb-4">Register to my website!</p>

      <div class="form-row mb-4">
        <div class="col">
          <!-- Name -->
          <input type="text" id="defaultRegisterFormFirstName" class="form-control" placeholder="Name">
        </div>
      </div>

      <div class="form-row mb-0">
        <div class="col">
          <!-- Date -->
          <input type="date" id="defaultRegisterFormDate" class="form-control" placeholder="Born">
          <small id="defaultRegisterFormPasswordHelpBlock" class="form-text text-muted mb-4">
            Choose your born date
          </small>
        </div>
      </div>

      <!-- E-mail -->
      <input type="email" id="defaultRegisterFormEmail" class="form-control mb-4" placeholder="E-mail">

      <div class="form-row mb-4">
        <div class="col">
          <!-- Username-->
          <input type="text" id="defaultRegisterFormFirstName" class="form-control" placeholder="Username">
        </div>
      </div>

      <!-- Password -->
      <div class="form-row mb-2">
        <div class="col">
          <input type="password" id="defaultRegisterFormPassword" class="form-control" placeholder="Password" aria-describedby="defaultRegisterFormPasswordHelpBlock">

        </div>
      </div>

      <div class="form-row mb-0">
        <div class="col">
          <input type="password" id="defaultRegisterFormPassword" class="form-control" placeholder="Password Confirmation" aria-describedby="defaultRegisterFormPasswordHelpBlock">
          <small id="defaultRegisterFormPasswordHelpBlock" class="form-text text-muted mb-4">
            At least 8 characters and 1 digit
          </small>

        </div>
      </div>

      <!-- Sign up button -->
      <button class="btn btn-info mb-4 btn-block" type="submit" formaction="story_3_home.html" >Sign up</button>

    </form>
    <!-- Default form register end -->

  </div>
</div>
{% endblock content %}

story_5/templates/story_5_jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class=" row  mx-0 my-3 px-0 py-3 d-flex flex-md-row justify-content-center">

    <!-- Default form register start -->
    <form class="col-12 col-lg-4 section  mr-lg-2 p-3 mb-3 mb-lg-auto"
      method="POST" action="{% url 'story_5:add_activity' %}">

      <div class="text-left title-3">
        Add your activity here! 
      </div>
      <br>
      {% csrf_token %}
      {{ form }}

      <br>
      {% comment %} <div class="text-center"> {% endcomment %}
      <button class="btn btn-info mb-0 " type="submit">Add Activity</button>
      {% comment %} </div> {% endcomment %}
    </form>

    <div class="section col-12 col-lg-5 ml-lg-2 p-3">
    
    <div class="row mb-3">
      <span class="col  title-3">
        Activity List 
      </span>
      <span class="col-auto ">
        <a href="{% url 'story_5:delete_all' %}" class="btn btn-danger mx-auto">Delete All</a>
      </span>
      <br>
    </div>

      {% for activity in activity_dict %}
      <div class="activity-card  mb-3 p-2">
        <span class="font-weight-bold">{{ activity.name }}</span> @ {{ activity.place }}<br>
        {{ activity.date|date:"D, d-m-Y" }} {{ activity.time|date:"G:i" }}   <br>
        {% for category in activity.category.split %}
        <span class="">#{{ category }}</span>
        {% endfor %} <br>
        {% comment %} <br> {% endcomment %}
      </div>
        {% endfor %}
    </div>

  </div>
</div>
{% endblock content %}